spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    activate:
      on-profile: dev
  thymeleaf:
name: "Development Environment"
server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: testing
name: "Testing"
server:
  port: 8000


